<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MayNghien.Infrastructures\MayNghien.Infrastructures\MayNghien.Infrastructures.csproj" />
    <ProjectReference Include="..\Todo.Commons\Todo.Commons.csproj" />
    <ProjectReference Include="..\Todo.DTOs\Todo.DTOs.csproj" />
    <ProjectReference Include="..\Todo.Models\Todo.Models.csproj" />
    <ProjectReference Include="..\Todo.Domain\Todo.Domain.csproj" />
  </ItemGroup>

</Project>
